name: Build Air Alert UA APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet requests telethon

      - name: Flet Build APK
        run: |
          echo "y" | flet build apk --verbose

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AirAlertUA-Release-APK
          path: build/apk/*.apk
